### ISSUE TITLE
感谢祭训练叶月出现时报错卡死

### ISSUE THREAD

**Issue by zzz7226226zzz** [biuuu/ShinyColors#69]
![image](https://user-images.githubusercontent.com/18678360/178336920-48ab6e70-e954-4c80-bbb9-574efe5c974e.png)
Uncaught (in promise) TypeError: i.includes is not a function
    at Object.apply (偶像大师ShinyColors汉化.user.js:19:92669)
    at t.value (5013-52db84366dbbb08862a3.chunk.js:1:236184)
    at 5013-52db84366dbbb08862a3.chunk.js:1:233414
    at async Promise.all (index 1)

**Comment by biuuu** [comment]
更新到1.9.4看好了没

**Comment by zzz7226226zzz** [comment]
大佬神速！感谢
